DROP USER c##movie CASCADE;
CREATE USER c##movie IDENTIFIED BY movie DEFAULT TABLESPACE users TEMPORARY TABLESPACE temp PROFILE DEFAULT;
GRANT CONNECT, RESOURCE TO c##movie;
GRANT CREATE VIEW, CREATE SYNONYM TO c##movie;
GRANT UNLIMITED TABLESPACE TO c##movie;
ALTER USER c##movie ACCOUNT UNLOCK;
